// All 34 saved skills, CV tools, and Codex as requested.
export const toolbox = [
  "Next.js",
  "React",
  "Nuxt.js",
  "Vue 3",
  "Laravel",
  "TypeScript",
  "Claude Code",
  "Codex",
  "Cursor",
  "Figma",
  "VS Code",
  "HTML5",
  "CSS3",
  "JavaScript",
  "Tailwind CSS",
  "PHP",
  "Node.js",
  "REST API",
  "Expo",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Supabase",
  "Facebook Graph API",
  "Instagram API",
  "SerpAPI",
  "Google Ads API",
  "Google Search Console",
  "Microsoft Azure AD",
  "Stripe",
  "Meta Conversions API",
  "Google Reviews",
  "Git",
  "GitHub",
  "Agile Scrum",
  "CMS",
  "Lead capture",
  "SaaS",
  "Payment integration"
] as const;
